export const UPLOAD_TRACK_ATTEMPT = 'UPLOAD_TRACK_ATTEMPT';
export const UPLOAD_TRACK_SUCCESS = 'UPLOAD_TRACK_SUCCESS';
export const UPLOAD_TRACK_FAILURE = 'UPLOAD_TRACK_FAILURE';
export const SIGN_IN_SUCCESS = 'SIGN_IN_SUCCESS';
export const SIGN_IN_FAILURE = 'SIGN_IN_FAILURE';
export const EMPTY_USER = 'EMPTY_USER';
